# Week 1 - Getting started with R

## <span style="color:#1A9FFF">Workshop outline
<!-- 
THIS IS A R MARKDOWN CELL.
THE CONTENT FOLLOWS R MARKDOWN STYLES.
FOR MORE INFO, YOU MAY REFER TO https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf
-->

* Setup
    + Setting up R for Jupyter notebook
<!--    + Installing R
        + Installing Jupyter Notebook
        + Working with Jupyter Notebook -->
    + Introduction to Jupyter Notebook
<!--    + R Markdown
        + R codes 
        + Creating slides from Jupyter notebook-->
* R Fundamentals
    + Data types
<!--    + Numerics
        + Characters
        + Logicals
        + Factors -->
    + Task 1
    + Data structures
<!--    + Vectors
        + Matrices
        + Arrays
        + Lists
        + Data Frames -->
    + Commands
<!--    + c 
        + str
        + summary
        + subset
        + help -->
    * Task 2 & 3
      

* Getting started
    + Reading data from files
<!--    + read.csv
        + read.table -->
    + Task 4
    + Exploring new packages
<!--    + Installing new packages
        + Reading documents -->
    + Basic statistics
<!--    + Mean
        + Median
        + Standard Deviation
        + Variance -->

## <span style="color:#1A9FFF">Setting up R for Jupyter notebook

* Installing R
* Installing Python (Required by Jupyter notebook)
* Installing Jupyter notebook
* Running Jupyter notebook


## <span style="color:#1A9FFF">Windows fan

1. Installing the R language
    * Installation package: 
        + https://cran.r-project.org/bin/windows/base/
    * Verification:
        + In command prompt, type **R** `print(R)`
            + If the command is not recognised, either
                1. Replace "R" with C:\"Program Files"\R\R-[version]\bin\R
                2. Set up environment variables on your machine
                    + == Google Keywords: add windows environment variable for r == 


* Install Python
    * Verify Python version installed
        1. In command prompt, type **python** and check the version
        * If no python version is installed, install python using Anaconda distribution https://www.anaconda.com/download/ (reference http://jupyter.readthedocs.io/en/latest/install.html)


* Running Jupyter Notebook
    1. In command prompt, type **jupyter notebook**

## <span style="color:#1A9FFF">Mac OS fan

1. Installing the R language
    * Installation package: 
        + https://cran.r-project.org/bin/macosx/
    * Verification:
        + In command prompt, type Rscript

* Install Python
    * Verify Python version installed
        1. In command prompt, type **python** and check the version
        * If no python version is installed, install python using Anaconda distribution https://www.anaconda.com/download/ (reference http://jupyter.readthedocs.io/en/latest/install.html)


* Running Jupyter Notebook
    1. In command prompt, type **jupyter notebook**

* install.packages(c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest'))
* devtools::install_github('IRkernel/IRkernel')
* IRkernel::installspec()


## <span style="color:#1A9FFF">Introduction to Jupyter notebook

### <span style="color:#1A9FFF">Creating a new notebook
1. File
2. New notebook
3. Select corresponding kernel (R)

### <span style="color:#1A9FFF">Cells
* A adds a cell
* X removes a cell
* Markdown
    + M convert cell to markdown
* Code
    + Press Y to convert cell to code


### <span style="color:#1A9FFF">Explore with references below
    * https://www.cheatography.com/weidadeyue/cheat-sheets/jupyter-notebook/
    * https://www.dataquest.io/blog/jupyter-notebook-tips-tricks-shortcuts/

This is a markdown cell. Markdown cells can have many different formatting. They can even accept CSS formats

<span style="color:#f22">I</span>
<span style="color:#f2f">can</span>
<span style="color:#22f">be</span>
<span style="color:#2ff">as</span>
<span style="color:#2f2">colorful</span>
<span style="color:#2f2">as</span>
<span style="color:#ff2">a</span>
<span style="color:#f22">rainbow</span>

For more, refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

In [1]:
print("This is a code cell")
print("Hello world")
1+1

[1] "This is a code cell"
[1] "Hello world"


[1] 2

### <span style="color:#1A9FFF">Presentation using Jupyter notebook

1. Open command prompt/terminal
2. execute command: 

jupyter nbconvert [ipynb location] --to slides --post serve

## <span style="color:#1A9FFF">Introduction to R

### <span style="color:#1A9FFF"> Basic data types

1. Numeric - 1,2,3,4,5...
2. Characters - A,B,C,a,b,c
3. Logicals - TRUE, FALSE
4. Factors - 1:Apple, 2:Orange, 3:Pear

In [25]:
fruits <- c("Apple", "Orange", "Pear", "Pear", "Orange")
print("This is a character vector")
class(fruits)
print(fruits)

[1] "This is a character vector"


[1] "character"

[1] "Apple"  "Orange" "Pear"   "Pear"   "Orange"


In [26]:
fruits <- as.factor(fruits)
print("This is a factor")
class(fruits)
print(fruits)
str(fruits)

[1] "This is a factor"


[1] "factor"

[1] Apple  Orange Pear   Pear   Orange
Levels: Apple Orange Pear
 Factor w/ 3 levels "Apple","Orange",..: 1 2 3 3 2


### <span style="color:#1A9FFF">Basic data structures
<!--    + Vectors
        + Matrices
        + Arrays
        + Lists
        + Data Frames -->

1. Vector: 1-D array of same data type
2. Matrices: 2-D array of same data type
3. Arrays: >2-D array of same data type
3. List: Ordered collection of objects
4. Data frame: Columns of data of varying data types. Main data structure in R.

### <span style="color:#1A9FFF">Basic R commands
<!--    + c 
        + str
        + summary
        + subset
        + help -->

#### <span style="color:#1A9FFF">Vectors
Lets create some vectors

In [3]:
# Create numeric vector 'a'
a <- c(1,2,3)
print("structure of a")
str(a)
print("class of a")
class(a)

[1] "structure of a"
 num [1:3] 1 2 3
[1] "class of a"


[1] "numeric"

#### <span style="color:#1A9FFF">Matrices

How do we create matrices

In [4]:
help(matrix)

Basic description of the function
![help1](help1.png)


Inputs for the function
![help2](help2.png)

Elaboration on how the function handles normally and abnormally
![Help part 3](help3.png)

Examples and other related functions
![help4](help4.png)

In [29]:
# Create numeric matrix b, c, d
b <- matrix(c(1,2,3,4,5,6), nrow=3, ncol=2)
print(b)

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6


In [30]:
c <- matrix(c(1,2,3,4,5,6), nrow=3, ncol=2, byrow=FALSE)
print(c)


     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6


In [31]:
d <- matrix(c(1,2,3,4,5,6), nrow=3, ncol=2, byrow=TRUE)
print(d)

     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6


### Task 1: Create a list containing some brand names (automobile, apparels, phones etc)
hint: search the help for list

"List" help uses "..." ellipses, therefore accepts all named inputs and will try to match in the definition. Some inherit from the parent classes.
![list help](list.png)

In [6]:
cars <- list(volkwagen=c("golf", "passat", "polo"), toyota=c("altis", "prius", "sienta"))
str(cars)

List of 2
 $ volkwagen: chr [1:3] "golf" "passat" "polo"
 $ toyota   : chr [1:3] "altis" "prius" "sienta"


### <span style="color:#1A9FFF">Data Frames

#### Main workhorse of R
* Tabular format
    + Columns of variables
    + Data type doesn't have to be the same between columns

####  esoph dataset: Smoking, Alcohol and (O)esophageal Cancer

In [7]:
# load esoph data
data(esoph)
# inspect data
str(esoph)

'data.frame':	88 obs. of  5 variables:
 $ agegp    : Ord.factor w/ 6 levels "25-34"<"35-44"<..: 1 1 1 1 1 1 1 1 1 1 ...
 $ alcgp    : Ord.factor w/ 4 levels "0-39g/day"<"40-79"<..: 1 1 1 1 2 2 2 2 3 3 ...
 $ tobgp    : Ord.factor w/ 4 levels "0-9g/day"<"10-19"<..: 1 2 3 4 1 2 3 4 1 2 ...
 $ ncases   : num  0 0 0 0 0 0 0 0 0 0 ...
 $ ncontrols: num  40 10 6 5 27 7 4 7 2 1 ...


In [8]:
head(esoph)

agegp alcgp     tobgp    ncases ncontrols
1 25-34 0-39g/day 0-9g/day 0      40       
2 25-34 0-39g/day 10-19    0      10       
3 25-34 0-39g/day 20-29    0       6       
4 25-34 0-39g/day 30+      0       5       
5 25-34 40-79     0-9g/day 0      27       
6 25-34 40-79     10-19    0       7

### Task 2: Select only the first row.

Hint: Look at the help file for head or google for other creative solutions

In [9]:
head(esoph, n=1)

agegp alcgp     tobgp    ncases ncontrols
1 25-34 0-39g/day 0-9g/day 0      40

In [10]:
esoph[1,]

agegp alcgp     tobgp    ncases ncontrols
1 25-34 0-39g/day 0-9g/day 0      40

### Task 3: Select only 1 variable.

In [11]:
esoph$agegp

[1] 25-34 25-34 25-34 25-34 25-34 25-34 25-34 25-34 25-34 25-34 25-34 25-34
[13] 25-34 25-34 25-34 35-44 35-44 35-44 35-44 35-44 35-44 35-44 35-44 35-44
[25] 35-44 35-44 35-44 35-44 35-44 35-44 45-54 45-54 45-54 45-54 45-54 45-54
[37] 45-54 45-54 45-54 45-54 45-54 45-54 45-54 45-54 45-54 45-54 55-64 55-64
[49] 55-64 55-64 55-64 55-64 55-64 55-64 55-64 55-64 55-64 55-64 55-64 55-64
[61] 55-64 55-64 65-74 65-74 65-74 65-74 65-74 65-74 65-74 65-74 65-74 65-74
[73] 65-74 65-74 65-74 65-74 65-74 75+   75+   75+   75+   75+   75+   75+  
[85] 75+   75+   75+   75+  
Levels: 25-34 < 35-44 < 45-54 < 55-64 < 65-74 < 75+

In [12]:
esoph[,1]

[1] 25-34 25-34 25-34 25-34 25-34 25-34 25-34 25-34 25-34 25-34 25-34 25-34
[13] 25-34 25-34 25-34 35-44 35-44 35-44 35-44 35-44 35-44 35-44 35-44 35-44
[25] 35-44 35-44 35-44 35-44 35-44 35-44 45-54 45-54 45-54 45-54 45-54 45-54
[37] 45-54 45-54 45-54 45-54 45-54 45-54 45-54 45-54 45-54 45-54 55-64 55-64
[49] 55-64 55-64 55-64 55-64 55-64 55-64 55-64 55-64 55-64 55-64 55-64 55-64
[61] 55-64 55-64 65-74 65-74 65-74 65-74 65-74 65-74 65-74 65-74 65-74 65-74
[73] 65-74 65-74 65-74 65-74 65-74 75+   75+   75+   75+   75+   75+   75+  
[85] 75+   75+   75+   75+  
Levels: 25-34 < 35-44 < 45-54 < 55-64 < 65-74 < 75+

### <span style="color:#1A9FFF">Basic statistics
<!--    + Mean
        + Median
        + Standard Deviation
        + Variance -->

In [13]:
data(airquality)
str(airquality)

'data.frame':	153 obs. of  6 variables:
 $ Ozone  : int  41 36 12 18 NA 28 23 19 8 NA ...
 $ Solar.R: int  190 118 149 313 NA NA 299 99 19 194 ...
 $ Wind   : num  7.4 8 12.6 11.5 14.3 14.9 8.6 13.8 20.1 8.6 ...
 $ Temp   : int  67 72 74 62 56 66 65 59 61 69 ...
 $ Month  : int  5 5 5 5 5 5 5 5 5 5 ...
 $ Day    : int  1 2 3 4 5 6 7 8 9 10 ...


#### Mean

In [14]:
mean(airquality$Wind)

[1] 9.957516

In [15]:
mean(airquality$Solar.R)

[1] NA

In [16]:
summary(airquality)

     Ozone           Solar.R           Wind             Temp      
 Min.   :  1.00   Min.   :  7.0   Min.   : 1.700   Min.   :56.00  
 1st Qu.: 18.00   1st Qu.:115.8   1st Qu.: 7.400   1st Qu.:72.00  
 Median : 31.50   Median :205.0   Median : 9.700   Median :79.00  
 Mean   : 42.13   Mean   :185.9   Mean   : 9.958   Mean   :77.88  
 3rd Qu.: 63.25   3rd Qu.:258.8   3rd Qu.:11.500   3rd Qu.:85.00  
 Max.   :168.00   Max.   :334.0   Max.   :20.700   Max.   :97.00  
 NA's   :37       NA's   :7                                       
     Month            Day      
 Min.   :5.000   Min.   : 1.0  
 1st Qu.:6.000   1st Qu.: 8.0  
 Median :7.000   Median :16.0  
 Mean   :6.993   Mean   :15.8  
 3rd Qu.:8.000   3rd Qu.:23.0  
 Max.   :9.000   Max.   :31.0  
                               

In [17]:
mean(airquality$Solar.R, na.rm=TRUE)

[1] 185.9315

#### Standard Deviation

In [18]:
sd(airquality$Solar.R, na.rm=TRUE)

[1] 90.05842

#### What exactly is standard deviation??

![gaussian](stddev.png)

#### Variance

In [19]:
var(airquality$Solar.R, na.rm=TRUE)

[1] 8110.519

## <span style="color:#1A9FFF">Getting started

More often than not, you often find yourself with a file containing your data. This can be either a txt or csv file or some other format.

### <span style="color:#1A9FFF">Reading data from files
<!--    + read.csv
        + read.table -->

* CSV files can be loaded using **read.csv**


In [20]:
help(read.csv)

* Similarly, csv data can be loaded using **read.table**


### Task 4: Identify the functional difference in these two operations

### <span style="color:#1A9FFF">Exploring new packages
<!--    + Installing new packages
        + Reading documents -->

So, Google suggest that your problem could be solved by a package that you have never seen before... What do you do now?

#### Check if such package is already installed.

In [52]:
library(nnet)

ERROR: Error in library(nnet): there is no package called 'nnet'


#### Install missing packages

In [22]:
install.packages("nnet",repos = "http://cran.us.r-project.org")
library(nnet)

Installing package into 'C:/Users/e140025/Documents/R/win-library/3.2'
(as 'lib' is unspecified)
Warning message:
"package 'nnet' is in use and will not be installed"

In [50]:
detach("package:nnet", unload=TRUE)
remove.packages("nnet")