## Operations with basic data structures

During the workshop, we have shown that a column of data within a data frame is essentially a vector. It can be used to perform various operations when paired with different data types. In the following section, you can try out the operations it can perform.

Exercise 1.1. Declare two vectors `x <- 1:4`, `y <- 0:10`, `z <- seq(0, 5, 0.5)`. This is commonly used in R to quickly declare a range of values. 

In [49]:
# code for Exercise 1.1:
x = 1:4
y = 0:10
z = seq(0, 5, 0.5)
x
y
z

[1] 1 2 3 4

[1]  0  1  2  3  4  5  6  7  8  9 10

[1] 0.0 0.5 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0

Exercise 1.2. Try adding them together using `x + y` and `y + z`. Did they work? What happened? 

In [20]:
# code for Exercise 1.2:
x + y
y + z
z

Warning message in x + y:
"longer object length is not a multiple of shorter object length"

[1]  1  3  5  7  5  7  9 11  9 11 13

[1]  0.0  1.5  3.0  4.5  6.0  7.5  9.0 10.5 12.0 13.5 15.0

[1] 0.0 0.5 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0

Exercise 1.3. Some functions will be performed element-wise within the vector e.g. `log(x)` while others like `sum(x)` returns a single value after aggregating all values. Keep this in mind and always refer to the documentation to get the output you require.

In [11]:
# code for Exercise 1.3:
log(x)
sum(x)
divide(x)

[1] 0.0000000 0.6931472 1.0986123 1.3862944

[1] 10

ERROR: Error in divide(x): could not find function "divide"


## Logical vectors
We have also seen some vector that stores `True` or `False` values. While its utility is not immediately apparent to you during the workshop, it is actually a product from Boolean conditions e.g. *to check if x equals 2:* `x == 2`, which can then used for selection or subsetting values.

Exercise 1.4. Using the vectors we have declared, try `y > 5` and `y[y > 5]` 

What happened? You can also try other Boolean expressions like `!=, ==, >=, <`

In [14]:
# code for Exercise 1.4:
y > 5
y[y > 5]
y[y != 2]

[1] FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE

[1]  6  7  8  9 10

[1]  0  1  3  4  5  6  7  8  9 10

Exercise 1.5. You can also use them to compare vector values by element. Declare a vector `v <- c(-1, pi, 2, Inf)` and compare it against `x`.

In [19]:
# code for Exercise 1.5:
v = c(-1, pi, 2, Inf)
v == x
v <= x

[1] FALSE FALSE FALSE FALSE

[1]  TRUE FALSE  TRUE FALSE

Exercise 1.6. Sometimes we are only interested in certain sections of the vector, so we will only extract the desired elements via indexing. For example, let's try `y[1:5]`. How does it differ from `y[y > 5]`? How will you extract the 2nd, 5th and 9th element of `z` into a new vector of [0.5, 2, 4]?

In [56]:
# code for Exercise 1.6:
y[1:5]
z[2]
z[5]
z[9]

z[c(2,5,9)]


[1] 0 1 2 3 4

[1] 0.5

[1] 2

[1] 4

[1] 0.5 2.0 4.0

## Linear algebra (optional)
Though built for computational statistics, R can also be a powerful tool to compute linear algebra, just like MATLAB. In this small segment, let's try out some matrix operations that we can do in R.

Exercise 1.7. Declare 2 matrices `A` & `B` as shown below using the tricks you have learnt. 

\begin{equation*}
A=
\begin{bmatrix}
1&2&3&4\\
5&6&7&8\\
9&10&11&12
\end{bmatrix}
\end{equation*}

\begin{equation*}
B=
\begin{bmatrix}
2&8&14&20\\
4&10&16&22\\
6&12&18&24
\end{bmatrix}
\end{equation*}

How do you perform `addition`, `element-wise multiplication` and `matrix multiplication` on these two matrices?

In [38]:
# code for Exercise 1.7:
A = matrix(c(1,2,3,4,5,6,7,8,9,10,11,12), nrow=3, ncol=4, byrow= TRUE)
print(A)
B = matrix(c(2,4,6,8,10,12,14,16,18,20,22,24), nrow=3, ncol=4)
print(B)

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8
[3,]    9   10   11   12
     [,1] [,2] [,3] [,4]
[1,]    2    8   14   20
[2,]    4   10   16   22
[3,]    6   12   18   24


Exercise 1.8. Find out how to compute the matrix's inverse, determinant and eigenvalues/vectors.

In [39]:
# code for Exercise 1.8:

In [40]:
A + B

[,1] [,2] [,3] [,4]
[1,]  3   10   17   24  
[2,]  9   16   23   30  
[3,] 15   22   29   36

In [41]:
A * B

[,1] [,2] [,3] [,4]
[1,]  2    16   42   80 
[2,] 20    60  112  176 
[3,] 54   120  198  288

In [45]:
A[1:3,1:4]+B[1:3,1:4]

[,1] [,2] [,3] [,4]
[1,]  3   10   17   24  
[2,]  9   16   23   30  
[3,] 15   22   29   36

In [46]:
help(matrix)

In [57]:
inverse[A(1:3,1:3)]

ERROR: Error in eval(expr, envir, enclos): object 'inverse' not found


In [58]:
t(A) %*% B

[,1] [,2] [,3] [,4]
[1,]  76  166  256  346 
[2,]  88  196  304  412 
[3,] 100  226  352  478 
[4,] 112  256  400  544